### ISSUE TITLE
IETF Draft calls it Sensor Measurement Lists not Sensor Markup Language

### ISSUE THREAD

**Issue by lanzafame** [objenious/senml#2]
Not sure if this change is intentional but it would be great to get a clarification.

**Comment by jfbus** [comment]
My fault. When we started, it was called "Markup Language", and the name stuck...

I'll fix it.

**Comment by jfbus** [comment]
Thanks

**Comment by lanzafame** [comment]
No worries. Thanks for the quick clarification.
